### ISSUE TITLE
Migration guide references the incorrect Ops Manager API version

### ISSUE THREAD

**Issue by mingxiao** [pivotal-cf/docs-tiledev#100]
Hello, on this page for 2.6
https://docs.pivotal.io/tiledev/2-6/migrating-syslog-configuration.html

Towards the end, the link:  Retrieving syslog configuration for a product
redirects you to the 2.9 API docs.

This is the case for 2.7 and 2.8 as well

**Comment by mingxiao** [comment]
In 2.9, we switched to a different API specification, so the anchor tag will be different

**Comment by animatedmax** [comment]
@mingxiao Thank you for raising this issue. The links should now be correct.
