### ISSUE TITLE
Validators Listing

### ISSUE THREAD

**Issue by josephlewis42** [pivotal-cf/docs-tiledev#33]
Hi,

I can't seem to find a section on the types of validators/constraints available, I see `min`, `max` and `must_match_regex`, but nothing else. Would you mind adding a link/pointing me to the canonical source?

Thanks!

**Comment by radaeze** [comment]
Hi @josephlewis42. Sorry for taking a while to get to this. We have updated the docs to call out the types of constraints available. I believe `must_match_regex` is the only validator available. https://docs.pivotal.io/tiledev/2-3/property-template-references.html#integer

**Comment by josephlewis42** [comment]
Thanks @radaeze
