### ISSUE TITLE
manifest field of job_types.templates is not documented

### ISSUE THREAD

**Issue by maplain** [pivotal-cf/docs-tiledev#45]
only name, release, concumes, provides are listed here: https://docs.pivotal.io/tiledev/2-3/property-template-references.html#job-template.

However, there is another field called `manifest` for a `job_type`. its meaning and implication, how it's used by opsman to put together a manifest is not clear.

**Comment by radaeze** [comment]
@maplain Thanks for the feedback. I am not entirely sure what information you are looking for. There is a `manifest` entry under the `job_types` header. This page might also help with defining how the manifest works: https://docs.pivotal.io/tiledev/2-3/property-template-references.html#property-values. If you are having a specific problem you can also try checking the Pivotal Support Community Portal: https://community.pivotal.io/s/

**Comment by maplain** [comment]
@radaeze on this page: https://docs.pivotal.io/tiledev/2-3/property-template-references.html#job-template.
`job templates` is defined as `array of hashes` and `Each element has the following fields:`, i.e: name, release, consumes, provides. 
however, there is another field called `manifest` that is missing. It essentially corresponds to `properties` field defined for a job in Bosh Manifest: https://bosh.io/docs/manifest-v2/#instance-groups. This field is very important for developing a tile and configuring a job, but it's missing from documentation now.

**Comment by radaeze** [comment]
@maplain I think this might be a case of docs structure. I am not sure how what you are asking for is distinct from [manifest](https://docs.pivotal.io/tiledev/2-3/property-template-references.html#job-manifest).
