### ISSUE TITLE
Confusion about Kiln vs Tile Generator

### ISSUE THREAD

**Issue by markthemarkest** [pivotal-cf/docs-tiledev#66]
Hi,

My team is releasing a tile version of our software, and we're a bit confused. This documentation references and recommends Tile Generator: https://github.com/cf-platform-eng/tile-generator

However, several of my peers who have created tiles in the past suggested Kiln: https://github.com/pivotal-cf/kiln

They both appear to be maintained by Pivotal, and each came endorsed by different sources. Personally, I tried both tools, and had more success using Kiln. I'm curious whether we should investigate covering both tools and reasons to choose one over the other in the documentation.

**Comment by jncd** [comment]
Hi @markthemarkest 
This documentation repository is maintained by technical writers, not developers or support engineering. If you have questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io
Or, if you belong to the Pivotal ISV Partner Program, see [Contact Us](https://docs.pivotal.io/tiledev/2-5/contacts.html).
