### ISSUE TITLE
Syslog Delegation permitted_peer

### ISSUE THREAD

**Issue by MirahImage** [pivotal-cf/docs-tiledev#84]
In the syslog migration guide,`permitted_peer` is incorrectly listed as a boolean. 
https://github.com/pivotal-cf/docs-tiledev/blob/9842578ce972f2a78a9e058b9e4f9d4f4eb112ea/migrating-syslog-configuration.html.md.erb#L62

**Comment by mlimonczenko** [comment]
Hello @MirahImage,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
